version: "3.9"

services:
  db:
    image: postgres:15
    container_name: hr_db
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  migrate:
    build:
      context: .
      dockerfile: deploy/migrate.Dockerfile
    command:
      [
        "-path",
        "/migrations",
        "-database",
        "postgres://hr_user:hr_pass@db:5432/hr_db?sslmode=disable",
        "up",
      ]
    depends_on:
      db:
        condition: service_healthy

  backend:
    build:
      context: ./backend
      dockerfile: deploy/backend.dev.Dockerfile
    user: "${UID}:${GID}"
    volumes:
      - ./backend:/app:Z
    working_dir: /app
    command: air
    ports:
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: deploy/frontend.dev.Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
